version: '2'

services:
  game-of-three-server:
    container_name: game-of-three-server
    build:
      context: ./game-of-three-server
      dockerfile: Dockerfile
    ports:
      - 8080:8080

  game-of-three-client:
    container_name: game-of-three-client
    build:
      context: ./game-of-three-client
      dockerfile: Dockerfile
    ports:
      - 3000:3000